graphhopper:
  datareader.file: us-west-latest.osm.pbf
  graph.location: /app/graph-cache
  graph.vehicles: bike
  graph.encoded_values: surface,road_class,road_environment,mtb_scale
  import.osm.ignored_highways: track,service,footway,steps,pedestrian,platform,construction,bridleway

  profiles:
    - name: bike
      vehicle: bike
      weighting: custom
      turn_costs: false
      custom_model_files: [bike.json]

    - name: gravel
      vehicle: bike
      weighting: custom
      turn_costs: false
      custom_model_files: [gravel.json]

    - name: mountain
      vehicle: bike
      weighting: custom
      turn_costs: false
      custom_model_files: [mountain.json]

  profiles_ch:
    - profile: bike
    - profile: gravel
    - profile: mountain

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0