graphhopper:
  datareader.file: us-west-latest.osm.pbf
  graph.location: /app/graph-cache
  graph.vehicles: bike,bike2,bike3

  profiles:
    - name: bike
      vehicle: bike
      weighting: fastest
      turn_costs: false
      custom_model_files: [bike.yml]
      
    - name: gravel
      vehicle: bike2  
      weighting: fastest
      turn_costs: false
      custom_model_files: [gravel.yml]
      
    - name: mountain
      vehicle: bike3
      weighting: fastest  
      turn_costs: false
      custom_model_files: [mountain.yml]

  profiles_ch:
    - profile: bike
    - profile: gravel
    - profile: mountain

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
